env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
    - REPO=mayadataio/dop-validator
    - PLAN=mayadataio/oep-e2eplan
sudo: required
services:
- docker
script:
- docker build -t $REPO:ci . ;
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then 
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker push $REPO:ci; 
  fi
