---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:

    - block:
  
        ## Generating the testname for deployment
        - include_tasks: /ansible-utils/create_testname.yml

        ## Record Start-Of-Test In Litmus Result CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'
        
        ## Getting username
        - name: Get username
          shell: cat /etc/secret-volume/username
          register: username

        ## Getting password     
        - name: Get password
          shell: cat /etc/secret-volume/password
          register: password

        ## Get the project details of the project on which the cluster is running
        - name: Fetch the project details of the project on which the cluster is running
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/project"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            status_code: 200
          register: project_details

        ## Saving Project id
        - name: Saving project id
          set_fact:
            project_id: "{{ project_details.json.data[0].id }}"

        ## Getting node details of the cluster
        ## Selecting the node which is in active state in the cluster
        - name: Getting the node details of the cluster which is in active state
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes?state=active&clusterId={{ cluster_id }}"
            method: GET
            url_username: "{{ username.stdout}}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200
          register: node_details

        ## Define variable node_id
        - set_fact:
            node_id: []

        ## Storing the id of the nodes in the cluster
        - name: Storing the id of nodes in the cluster
          set_fact:
            node_id: "{{ node_id  + [item.id] }}"
          loop: "{{ node_details.json.data }}"

        ## Labeling node-1 of the Cluster with controlPlaneNode=false and dataPlaneNode=true
        ## With the first element in the node_id list
        - name: Labeling node-1 of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node_id[0] }}/?action=labelnodes"
            method: POST
            url_username: "{{ username.stdout}}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            status_code: 202
            body_format: json
            body: '{"controlPlaneNode": false, "dataPlaneNode": true }'
          register: labelnode1

        ## Labeling node-2 of the Cluster with controlPlaneNode=true and dataPlaneNode=false
        ## With the second element in the node_id list
        - name: Labeling node-2 of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node_id[1] }}/?action=labelnodes"
            method: POST
            url_username: "{{ username.stdout}}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 202
            body: '{"controlPlaneNode": true, "dataPlaneNode": false }'
          register: labelnode2


        ## Labeling node-3 of the Cluster with controlPlaneNode=true and dataPlaneNode=false
        ## With the third element in the node_id list
        - name: Labeling node-3 of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node_id[2] }}/?action=labelnodes"
            method: POST
            url_username: "{{ username.stdout}}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body: '{"controlPlaneNode": true, "dataPlaneNode": false }'
            status_code: 202
          register: labelnode3

        ## Get active openebses
        - name: Get active openebses
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses?state=active&clusterId={{ cluster_id}}"
            method: GET
            url_username: "{{ username.stdout }}" 
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200
          register: openebses_active

        - block:
          
          - name: Fetching Job manifest
            set_fact:
              openebs_job_manifest: "{{ openebses_active.json.data[0].installationManifest }}"

          - name: Getting the openebses id
            set_fact:
              openebs_id: "{{ openebses_active.json.data[0].id }}"

          - name: Installing openebs on the cluster
            uri:
              url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses/{{ openebs_id }}?action=openebsinstall"
              method: POST
              url_username: "{{ username.stdout }}"
              url_password: "{{ password.stdout }}"
              force_basic_auth: yes
              return_content: yes
              body_format: json
              body: '{"yaml": {{ openebs_job_manifest }}}'
              status_code: 200
              headers:
                Content-Type: "application/json"
            register: openebs

          - name: Fetching Job Id to of openebsjob
            set_fact:
              openebs_job_id: "{{ openebs.json.id }}"
        
          - name: Fetch openebsjob details
            uri:
              url: "{{ director_url }}/v3/groups/{{ group_id}}/openebsjobs/{{ openebs_job_id }}"
              method: GET
              url_username: "{{ username.stdout }}"
              url_password: "{{ password.stdout }}"
              force_basic_auth: yes
              return_content: yes
              body_format: json
              status_code: 200
            register: openebs_job
            until: "openebs_job.json.state == 'Success'"
            delay: 10
            retries: 10
        
          when: openebses_active.json.data != []

        - block: 

          - name: Fetch openebses and create openebs
            uri:
              url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses"
              method: POST
              url_username: "{{ username.stdout }}"
              url_password: "{{ password.stdout }}"
              force_basic_auth: yes
              return_content: yes
              body_format: json
              body: '{ "clusterId": "{{ cluster_id }}","creatorId": "{{ group_id }}","projectId": "{{ project_id }}","templateId": "{{ template_id }}","namespace": "{{ namespace }}","defaultDirectory": "{{ default_directory }}","dockerRegistry": "{{ docker_registry }}","includeDeviceFilters": "{{ include_device_filters }}","excludeDeviceFilters": "{{ exclude_device_filters }}","cpuResourceLimit": "{{ cpu_resource_limit }}","memoryResourceLimit": " {{ memory_resource_limit }}","installationMode": "{{ installation_mode }}" }'
              status_code: 201
            register: install_openebs

          ## Fetching installation manifest
          - name: Get manifest for installing openebs
            set_fact:
              installopenebs: "{{ install_openebs.json.installationManifest }}"

          ## Getting the id 
          - name: Getting the id
            set_fact:
              openebs_id: "{{ install_openebs.json.id }}"

          ## Installing openebs
          - name: Installing openebs on the cluster
            uri:
              url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses/{{ openebs_id }}/?action=openebsinstall"
              method: POST
              url_username: "{{ username.stdout }}"
              url_password: "{{ password.stdout }}"
              force_basic_auth: yes
              return_content: yes
              body_format: json
              body: '{"yaml": {{ installopenebs }}}'
              status_code: 200
            register: openebs

          ## Fetching job ID
          - name: Fetching Job Id to of openebsjob
            set_fact:
              openebs_job_id: "{{ openebs.json.id }}"

          - name: Fetch openebsjob details
            uri:
              url: "{{ director_url }}/v3/groups/{{ group_id}}/openebsjobs/{{ openebs_job_id }}"
              method: GET
              url_username: "{{ username.stdout }}"
              url_password: "{{ password.stdout }}"
              force_basic_auth: yes
              return_content: yes
              body_format: json
              status_code: 200
            register: openebs_job
            until: "openebs_job.json.state == 'Success'"
            delay: 10
            retries: 30

          when: openebses_active.json.data == []

        ## Checking the data plane label on the first node
        - name: Checking the label on first node of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node_id[0] }}"
            method: GET
            url_username: "{{ username.stdout}}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200
          register: node1
          failed_when: "node1.json.nodeType['mayadata.io/data-plane'] != 'true'"

        ## Checking the data plane label on the second node
        - name: Checking the label on the second node of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node_id[1] }}"
            method: GET
            url_username: "{{ username.stdout}}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200
          register: node2
          failed_when: "node2.json.nodeType['mayadata.io/control-plane'] != 'true'"        

        ## Checking the data plane label on the third node
        - name: Checking the label on the third node of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node_id[2] }}"
            method: GET
            url_username: "{{ username.stdout}}"
            url_password: "{{ password.stdout}}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200
          register: node3
          failed_when: "node3.json.nodeType['mayadata.io/control-plane'] != 'true'"

        ## Checking the openebs Installation    
        - name: Fetch OpenEBS control plane pods state
          shell: kubectl get pods -n {{ namespace }}  | grep {{ item }} | awk '{print $3}' | awk -F':' '{print $1}' | tail -n 1
          register: app_status
          until: app_status.stdout == 'Running'
          with_items:
            - "{{ openebs_components }}"
          retries: 30
          delay: 10

        ## Get the container Status of the openebs pods
        - name: Get the container status of the openebs pods.
          shell: >
            kubectl get pod -n {{ namespace }} --no-headers
            -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | tr ' ' '\n' | uniq
          args:
            executable: /bin/bash
          register: containerStatus
          until: "containerStatus.stdout == 'true'"
          retries: 30
          delay: 10

        ## Checking if openebs is installed or not.
        - name: Check if openebs is already installed
          shell: kubectl get deploy --all-namespaces -l name=maya-apiserver --no-headers | awk '{print $1}' | wc -l
          args:
            executable: /bin/bash
          register: count_maya_api

        ## If openebs is installed in the cluster then get the namespace
        - name: Getting the namespace where openebs is installed 
          shell: kubectl get deploy --all-namespaces -l name=maya-apiserver --no-headers | awk '{print $1}'
          args:
            executable: /bin/bash
          register: openebs_namespace
          when: "count_maya_api.stdout == '1'"

        ## Removing the labels from the cluster nodes
        - include_tasks: /utils/openebs-label-cleanup.yml

        ## Deleting openebs from the cluster
        - include_tasks: /utils/openebs-cleanup.yml
          vars:
            namespace: "{{ openebs_namespace.stdout }}"
            
        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'