---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: configs-db-check
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: configs-db-check-litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: mayadataio/dop-validator:ci
        imagePullPolicy: IfNotPresent
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default  
          - name: NAMESPACE
            value: default              
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./litmus/director/configs-db/test.yaml -i /etc/ansible/hosts -v; exit 0"]
      imagePullSecrets:
      - name: oep-secret