---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
  
    ## Generating the testname for deployment
    - include_tasks: /ansible-utils/create_testname.yml

    ## RECORD START-OF-TEST IN LITMUS RESULT CR
    - include_tasks: /ansible-utils/update_litmus_result_resource.yml
      vars:
        status: 'SOT'
      
    - set_fact:
        director_url : "http://{{ director_ip }}:30380"

    ## Getting the username
    - name: Get username
      shell: cat /etc/secret-volume/username
      register: username

    ## Getting the password     
    - name: Get password
      shell: cat /etc/secret-volume/password
      register: password

    - block:

        ## Checking if openebs is already installed in the cluster
        - name: Check if openebs is already installed
          shell: kubectl get deploy --all-namespaces | grep maya-apiserver | awk '{print $1}' | wc -l
          args:
            executable: /bin/bash
          register: count_maya_api

        ## If openebs is installed in the cluster then get the namespace
        - name: Getting the namespace where openebs is installed 
          shell: kubectl get deploy --all-namespaces | grep maya-apiserver | awk '{print $1}'
          args:
            executable: /bin/bash
          register: openebs_namespace
          when: "count_maya_api.stdout == '1'"

        ## Delete openebs 
        - name: Deleting openebs
          shell: kubectl delete namespace {{ openebs_namespace.stdout }}
          args:
            executable: /bin/bash
          when: "count_maya_api.stdout == '1'"
          
        ## Fetch Project deatils
        - name: Fetch the project details
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/project"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            status_code: 200
          register: project_details

        ## Fetching project details
        - name: Fetching project details
          set_fact:
            project_id: "{{ project_details.json.data[0].id }}"
        
        ## Fetch node details of the cluster
        - name: Fetch node details of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/clusters/{{ cluster_id }}/nodes"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200
          register: node_cluster
        
        ## Fetch node-1 details of the cluster
        - name: Fetch node-1 details of the cluster
          set_fact:
            node1_id: "{{ node_cluster.json.data[0].id}}"
        
        ## Fetch node-2 details of the cluster
        - name: Fetch node-2 details of the cluster
          set_fact:
            node2_id: "{{ node_cluster.json.data[1].id}}"

        ## Labeling the node-1 of connected Cluster with controlPlaneNode=true and dataPlaneNode=true
        - name: Giving POST request on labelnodes
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node1_id }}/?action=labelnodes"
            method: POST
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body: '{"controlPlaneNode": true, "dataPlaneNode": true}'
            status_code: 202

        ## Labeling the node-2 of connected Cluster with controlPlaneNode=true and dataPlaneNode=flase
        - name: Giving POST request on labelnodes
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes/{{ node2_id }}/?action=labelnodes"
            method: POST
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body: '{"controlPlaneNode": true, "dataPlaneNode": false}'
            status_code: 202

        ## Creating openebs
        - name: Fetch openebses and create openebs
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses"
            method: POST
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body: "{ \"clusterId\": \"{{ cluster_id }}\",\"creatorId\": \"{{ group_id }}\",\"projectId\": \"{{ project_id }}\",\"templateId\": \"{{ template_id }}\",\"namespace\": \"{{ namespace }}\",\"defaultDirectory\": \"{{ default_directory }}\",\"dockerRegistry\": \"{{ docker_registry }}\",\"includeDeviceFilters\": \"{{ include_device_filters }}\",\"excludeDeviceFilters\": \"{{ exclude_device_filters }}\",\"cpuResourceLimit\": \"{{ cpu_resource_limit }}\",\"memoryResourceLimit\": \" {{ memory_resource_limit }}\",\"installationMode\": \"{{ installation_mode }}\" }"
            status_code: 201
          register: install_openebs

        ## Fetching installation manifest
        - name: Get manifest for installing openebs
          set_fact:
            installopenebs: "{{ install_openebs.json.installationManifest }}"

        - name: Getting the id
          set_fact:
            openebs_id: "{{ install_openebs.json.id }}"

        - name: Getting into the openebs installation stage and checking the id
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses/{{ openebs_id }}"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200

        ## Installing openebs
        - name: Installing openebs on the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses/{{ openebs_id }}/?action=openebsinstall"
            method: POST
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body: '{{ installopenebs }}'
            status_code: 200
          register: openebs
        
        ## Fetching job ID
        - name: Fetching Job Id to of openebsjob
          set_fact:
            openebs_job_id: "{{ openebs.json.id }}"
        
        - name: Fetch openebsjob details
          uri:
            url: "{{ director_url }}/v3/groups/1a14/openebsjobs/{{openebs_job_id}}"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            status_code: 200
          register: openebs_job
          until: openebs_job.json.jobStatus != ""
          delay: 10
          retries: 10
        
        ## Checking wether the openebs_job pod is in online state or not.
        - name: Checking phase of openebs_job 
          shell: echo "{{ openebs_job.json.jobStatus.phase }}"
          failed_when: "'{{ openebs_job.json.jobStatus.phase }}' != 'Online'"

        ## Removing the labels from the cluster nodes
        - include_tasks: ../../../utils/openebs-label-cleanup.yaml

        ## Deleting openebs from the cluster
        - include_tasks: ../../../utils/openebs-cleanup.yml
    
        ## Setting flag as Pass
        - set_fact:
            flag: "Pass"
        
      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'