apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cspc-external
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: "nodeName"
      dataRaidGroups:
      - blockDevices:
          - blockDeviceName: "dummyvalue"
      poolConfig:
        dataRaidGroupType: "stripe"
