#Use the following YAMLs to create a SPC.
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pools
  namespace: openebs
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pools
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
    - dummyvalue
    
