---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:

    - block:
  
        ## Generating the testname for deployment
        - include_tasks: /ansible-utils/create_testname.yml

        ## Record Start-Of-Test In Litmus Result CR
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'
               
        ## Getting username
        - name: Get username
          shell: cat /etc/secret-volume/username
          register: username

        ## Getting password     
        - name: Get password
          shell: cat /etc/secret-volume/password
          register: password

        ## Checking if openebs is already installed in the cluster
        - name: Check if openebs is already installed
          shell: kubectl get deploy --all-namespaces -l name=maya-apiserver --no-headers | awk '{print $1}' | wc -l
          args:
            executable: /bin/bash
          register: count_maya_api

        ## If openebs is installed in the cluster then get the namespace
        - name: Getting the namespace where openebs is installed 
          shell: kubectl get deploy --all-namespaces -l name=maya-apiserver --no-headers | awk '{print $1}'
          args:
            executable: /bin/bash
          register: openebs_namespace
          when: "count_maya_api.stdout == '1'"

        # Getting node details of the cluster
        ## Selecting the node which is in active state present in the cluster
        ## Retry till the data field in node details is empty
        - name: Getting the node details of the cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/nodes?state=active&clusterId={{ cluster_id }}"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body:
              status_code: 202
          register: node_details
          until: "node_details.json.data != []"
          delay: 2
          retries: 10

        ## Define variable node_id
        - set_fact:
            node_id: []
        
        ## Storing the node id of the nodes in the cluster
        - name: Storing the node id of node in the cluster
          set_fact:
            node_id: "{{ node_id  + [item.id] }}"
          loop: "{{ node_details.json.data }}"

        ## Removing the labels from the cluster nodes
        - name: Cleanup labels from the nodes
          include_tasks: /utils/openebs-label-cleanup.yml
          when: "count_maya_api.stdout == '1'"

        ## Deleting openebs from the cluster
        - name: Cleanup openebs from the cluster
          include_tasks: /utils/openebs-cleanup.yml
          vars:
            namespace: "{{ openebs_namespace.stdout }}"
          when: "count_maya_api.stdout == '1'"

        ## Fetch the projectid of the project where the cluster is running
        - name: Fetch the project details of the project where the cluster is running
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/project"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            status_code: 200
          register: project_details

        ## Saving Project id
        - name: Saving the project id
          set_fact:
            project_id: "{{ project_details.json.data[0].id }}"

        ## Fetch template_details
        - name: Fetch the template_details
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/openebstemplates?sort=id&order=desc"
            method: GET
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            status_code: 200
          register: template_details

        ## Fetching template_id
        - name: Fetching template_id
          set_fact:
            template_id: "{{ template_details.json.data[0].id }}"

        ## Passing the value for openebs creation in the cluster
        - name: Passing the values required for openebs creation
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses"
            method: POST
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body: '{ "clusterId": "{{ cluster_id }}","creatorId": "{{ group_id }}","projectId": "{{ project_id }}","templateId": "{{ template_id }}","namespace": "{{ namespace }}","defaultDirectory": "{{ default_directory }}","dockerRegistry": "{{ docker_registry }}","includeDeviceFilters": "{{ include_device_filters }}","excludeDeviceFilters": "{{ exclude_device_filters }}","cpuResourceLimit": "{{ cpu_resource_limit }}","memoryResourceLimit": " {{ memory_resource_limit }}","installationMode": "{{ installation_mode }}" }'         
            status_code: 201
          register: get_openebs

        - name: Saving the yaml for openebs installation
          set_fact:
            installopenebs: "{{ get_openebs.json.installationManifest }}"

        - name: Saving the id
          set_fact:
            openebsid: "{{ get_openebs.json.id }}"

        - name: Get the node1_id
          set_fact:
            node1_id: "{{ node_id[0].split('n')[1] }}"

        - name: Get the node2_id
          set_fact:
            node2_id: "{{ node_id[1].split('n')[1] }}"

        - name: Get the node3_id
          set_fact:
            node3_id: "{{ node_id[2].split('n')[1] }}"

        - name: Get the node4_id
          set_fact:
            node4_id: "{{ node_id[3].split('n')[1] }}"

        - block:
          
          - name: Get the node5_id
            set_fact:
              node5_id: "{{ node_id[4].split('n')[1] }}"
          
          - name: Labeling the nodes of the cluster
            uri:
              url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses/{{ openebsid }}/?action=selectopenebsnodes"
              method: POST
              url_username: "{{ username.stdout }}"
              url_password: "{{ password.stdout }}"
              force_basic_auth: yes
              return_content: yes
              body_format: json
              body: {
                      controlPlaneNodes": [ 
                        "{{ node1_id }}",
                        "{{ node2_id }}",
                        "{{ node3_id }}",
                        "{{ node4_id }}",
                        "{{ node5_id }}"
                      ],
                      dataPlaneNodes": [
                        "{{ node1_id }}",
                        "{{ node2_id }}",
                        "{{ node3_id }}",
                        "{{ node4_id }}",
                        "{{ node5_id }}"
                      ]
                    }
              status_code: 200
            register: labelnodes

          when: platform == "KONVOY" or platform == "RANCHER"

        - block:
          
          - name: Labeling the nodes of the cluster
            uri:
              url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses/{{ openebsid }}/?action=selectopenebsnodes"
              method: POST
              url_username: "{{ username.stdout }}"
              url_password: "{{ password.stdout }}"
              force_basic_auth: yes
              return_content: yes
              body_format: json
              body: {
                      controlPlaneNodes": [ 
                        "{{ node1_id }}"
                      ],
                      dataPlaneNodes": [
                        "{{ node1_id }}",
                        "{{ node2_id }}",
                        "{{ node3_id }}"
                      ]
                    }
              status_code: 200
            register: labelnodes

          when: platform == "AWS"

        ## Installing openebs
        - name: Installing openebs on the DOP self cluster
          uri:
            url: "{{ director_url }}/v3/groups/{{ group_id }}/openebses/{{ openebsid }}/?action=openebsinstall"
            method: POST
            url_username: "{{ username.stdout }}"
            url_password: "{{ password.stdout }}"
            force_basic_auth: yes
            return_content: yes
            body_format: json
            body: '{"yaml": {{ installopenebs }}}'
            status_code: 200
          register: res_openebs

        ## Checking the openebs Installation    
        - name: Fetch OpenEBS control plane pods state
          shell: kubectl get pods -n {{ namespace }}  | grep {{ item }} | awk '{print $3}' | awk -F':' '{print $1}' | tail -n 1
          register: app_status
          until: app_status.stdout == 'Running'
          with_items:
            - "{{ openebs_components }}"
          retries: 30
          delay: 10

        ## Get the container Status of the openebs pods
        - name: Get the container status of the openebs pods.
          shell: >
            kubectl get pod -n {{ namespace }} --no-headers
            -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | tr ' ' '\n' | uniq
          args:
            executable: /bin/bash
          register: containerStatus
          until: "containerStatus.stdout == 'true'"
          retries: 30
          delay: 10

        ## Checking the resource litmit is imposed perfectly or not
        - name: Getting the CPU limit of maya-api-server
          shell: kubectl get deploy maya-apiserver -n {{ namespace }} -o=jsonpath='{.spec.template.spec.containers[*].resources.limits.cpu}'
          args:
            executable: /bin/bash
          register: cpu_limit
          failed_when: "cpu_limit.stdout != cpu_resource_limit"

        ## Checking the resource litmit is imposed perfectly or not
        - name: Getting the Memory limit of maya-api-server
          shell: kubectl get deploy maya-apiserver -n {{ namespace }} -o=jsonpath='{.spec.template.spec.containers[*].resources.limits.memory}'
          args:
            executable: /bin/bash
          register: memory_limit
          failed_when: "memory_limit.stdout != memory_resource_limit"

        - name: Check if the device has been excluded or not.
          shell: >
              kubectl get blockdevice -n {{ namespace }} -o custom-columns=:.spec.path --no-headers
          args:
            executable: /bin/bash
          register: path_list
          failed_when: "exclude_device_filters in path_list.stdout"
          
        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CRhttps://github.com/mayadata-io/oep-e2e-gcp/blob/dc8f3585e5debe12a700220066b204a0b35cbb5c/stages/9-openebs-install-check/openebs-reinstallation.md)
        - include_tasks: /ansible-utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
