apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: delete-spc
  labels:
    name: minio
spec:
  ports:
    - port: 9000
      nodePort: 32701
      protocol: TCP
  selector:
    name: minio
  sessionAffinity: None
  type: NodePort

