---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: od-elasticsearch-check
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: od-elasticsearch-check-litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: mayadataio/dop-validator:ci
        imagePullPolicy: IfNotPresent
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default  
          - name: NAMESPACE
            value: default
          - name: ADMIN_USER
            value: admin
          - name: ADMIN_PASSWORD
            value: password
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./litmus/director/od-elasticsearch/test.yaml -i /etc/ansible/hosts -v; exit 0"]
      imagePullSecrets:
      - name: oep-secret