kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-external-cspc
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  cstorPoolCluster: cspc-external-volume
  replicaCount: "1"